spring:
  application:
    name: ipl-flash-sale

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ipl_flash_sale}
    username: ${SPRING_DATASOURCE_USERNAME:ipl_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ipl_pass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: booking-workers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.iplflash.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

redisson:
  address: ${REDIS_URL:redis://localhost:6379}

server:
  port: ${PORT:8080}
